### ISSUE TITLE
High-Precision AD HAT For Raspberry Pi, ADS1263 10-Ch 32-Bit ADC.

### ISSUE THREAD

**Issue by potaninmt** [MicrosoftDocs/dotnet-iot-assets#3]
I have High-Precision AD HAT For Raspberry Pi, ADS1263 10-Ch 32-Bit ADC. How I can read voltage from channels?

**Comment by CamSoper** [comment]
@SSRTC I'm sorry, I didn't see this question earlier.

I don't see a [device binding](https://github.com/dotnet/iot/blob/main/src/devices/README.md) for that ADC yet. You can still interact with it directly using `System.Device.Gpio`, but the product devs hang out in the [Discord community](https://discord.gg/kqWhBbj) and might have some ideas (or might even help you with building a device binding!)
